server:
  port: 8080
  servlet:
    context-path: /identity

url:
  root: "localhost:8080/identity"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
    username: root
    password: admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create
#      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#  sql:
#    init:
#      mode: never
#      mode: always
#      platform: mysql
#      data-locations:
#        - classpath:drop/drop_table.sql
#        - classpath:init/step_1_init_table.sql
#        - classpath:init/step_2_init_data.sql
#        - classpath:init/step_3_add_field.sql


logging:
  level:
    root: INFO
    com.npn.users: DEBUG
    org.mapstruct: DEBUG
    org.hibernate.orm.connections.pooling: WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-15t){faint} %clr(%-30.30c{1.}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p %-15t %-30.30c{1.} : %m%n%wEx"
  file:
    name: logs/application.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 7